# [Tutorial Link](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[7.5563e+31, 1.8014e+25, 8.1335e+32],
        [7.2436e+22, 7.5554e+28, 2.9635e+29],
        [2.2087e+03, 2.9386e+29, 7.1104e-04],
        [1.3556e-19, 1.8567e-01, 2.1017e-19],
        [7.5553e+28, 5.2839e-11, 7.5018e+28]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6080, 0.4230, 0.7691],
        [0.9935, 0.4115, 0.6263],
        [0.9735, 0.7888, 0.4551],
        [0.0337, 0.5336, 0.4262],
        [0.1783, 0.0810, 0.5809]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [3]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [4]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)   

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4545,  1.0206, -0.5352],
        [-0.8543, -0.6690,  1.0146],
        [-0.5899, -0.3079,  0.0666],
        [-1.5506,  2.0959, -1.3041],
        [-0.0212,  0.3484,  0.4389]])


In [5]:
print(x.size())

torch.Size([5, 3])


In [6]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2973,  1.2454, -0.3366],
        [-0.4525,  0.0906,  2.0088],
        [-0.5836,  0.4275,  0.0787],
        [-0.8299,  2.8192, -0.3057],
        [ 0.4022,  1.2608,  0.5051]])


In [7]:
print(torch.add(x, y))

tensor([[-0.2973,  1.2454, -0.3366],
        [-0.4525,  0.0906,  2.0088],
        [-0.5836,  0.4275,  0.0787],
        [-0.8299,  2.8192, -0.3057],
        [ 0.4022,  1.2608,  0.5051]])


In [8]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.2973,  1.2454, -0.3366],
        [-0.4525,  0.0906,  2.0088],
        [-0.5836,  0.4275,  0.0787],
        [-0.8299,  2.8192, -0.3057],
        [ 0.4022,  1.2608,  0.5051]])
